a=input('digite algo:')
print('o tipo primitivo desse valor é' , type(a))
print('só tem espaços?' , a.isspace())
print('é um número?', a.isnumeric())
print('é alfabetico?', a.isalpha())
print('é alfa numerico?', a.isalnum())
print('esta em maiusculas?', a.isupper())
print('esta em minusculas?', a.islower())
print('esta capitalizada?', a.istitle())
