nome=str(input('qual seu nome completo?')).strip()
print('analisando seu nome...')
print('seu nome em maiúsculo é {}' .format(nome.upper()))
print('seu nome em minúsculas é {}' .format(nome.lower()))
print('seu nome ao total tem {} letras' .format(len(nome)-nome.count(' ')))
print('seu primeiro nome tem {} letras' .format(nome.find(' ')))